language: ruby
cache: bundler
rvm:
  - 2.6.5

services:
  - postgresql
before_script:
  - gem install rmagick
  - psql -c 'create database cta_portfolio_test;' -U postgres
test:
  adapter: postgresql
  database: cta_portfolio_test
deploy:
  provider: heroku
  api_key:
    secure: "3ddcce24-2a3b-4f78-8a59-e98160ee63b8"
  github_token: ENV['GITHUB_ACCESS_TOKEN']
  keep-history: true
  verbose: true
  on:
    branch: main