language: ruby
cache: bundler
rvm:
  - 2.6.5

services:
  - postgresql
before_script:
  - gem install rmagick
  - psql -c 'create database cta_portfolio_test;' -U postgres
test:
  adapter: postgresql
  database: cta_portfolio_test
deploy:
  provider: heroku
  api_key:
    secure: dc682e5e22e1705ec805df5bab65650115fbd38f8ef868e37dd6ecd1565d32cdcace8044c93844598e850c880f39476fcdb96d8cbe8b1bbcae599540a55a2eba

