language: ruby
rvm:
  - 2.6.5
  - jruby
services:
  - postgresql
before_script:
  - gem install rmagick
  - psql -c 'create database cta_portfolio_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test