language: ruby
cache: bundler
rvm:
- 2.6.5
services:
- postgresql
before_script:
- gem install rmagick
- psql -c 'create database cta_portfolio_test;' -U postgres
test:
  adapter: postgresql
  database: cta_portfolio_test
deploy:
  provider: heroku
  api_key:
    secure: IihN1JvTdNiB54SmiQVwr2Wdts57g+6JnRrUFglqPTESe4TA7h3lmWXLvv/JsJJ99zLPqnuzC536eSTEOWTSFZDRsxKk8IATC3O/rTL195tEbgBeNUAX5H+fOd0ozUfrZb+bdQ36yNYsdk5n/ZgESVIFKMToIMsbUhnmcetTk+1QnGhbEtKncX9iiAL1Zz/7W57DZlLgI0vrG9WXU3X1c2yuM0yU5L4pA8sa1KjeLvV3is0JvtUafmER6pJuC6FGK7Ag74cDFLYok1hIl31NT2OUq9PeuNfmWp/zJipWuewaC048rDs/KriTGg8lci0OzulEdEmaylnIi2F1qoKQGz3Om6Yz6wbZru640dsEVRQnQaxmkyhoJyaJ6/wS8AsjUhYg6A/lVNGmjWJIvXeE9+lqnFDbcOjdDojgPe81t1UMZpqt8mJlf8g68vfXoWVBcpEruCSHRIJub51AdPsQkZeoCD4aSgitrBkMpCPRAuRH9UJZ2B8e16UBopx3iRWr58pSUogil1PACk8reXE+eYUa/sDRau/di4ETAB5i2BKlqBpusmwQx85YklyDu6RFfJvd3/1MYD5GD659qVPmhQblSmnLMb+ukyCt1Wdnp5An+N0ntLmHQ1wuPd+my0dHn3lLh48l0E3oAlJ5gwX8Uw/wATkMppVUhlUZNcKRQIo=
  app: cta_portfolio
  on:
    branch: main
  keep-history: true
  verbose: true
