language: ruby
cache: bundler
rvm:
  - 2.6.5

services:
  - postgresql
before_script:
  - gem install rmagick
  - psql -c 'create database cta_portfolio_test;' -U postgres
test:
  adapter: postgresql
  database: cta_portfolio_test
deploy:
  provider: heroku
  api_key:
    secure: 3ddcce24-2a3b-4f78-8a59-e98160ee63b8
  app: cta_portfolio # being app name on heroku which am deploying to.
  on:
    repo: colintalex/cta_portfolio # GitHub Repo
  keep-history: true
  verbose: true
  on:
    branch: main
